#define SECRET_SSID "INSERT_YOUR_WIFI_SSID"
#define SECRET_PASS "INSERT_YOUR_WIFI_PASSWORD"

#define MQTT_PORT 1883
#define MQTT_HOST "INSERT_YOUR_MQTT_HOST"
#define CLIENT_ID "INSERT_YOUR_MQTT_CLIENT_ID (uncomment if you want to use)"
#define MQTT_USERNAME "INSERT_YOUR_MQTT_USERNAME"
#define MQTT_PASSWORD "INSERT_YOUR_MQTT_PASSWORD"
